### ISSUE TITLE
Error at install

### ISSUE THREAD

**Issue by rikyperdana** [MarcHanin/drun#1]
Is this a bug or did I do anything wrong at the installation command?
![Screenshot from 2020-05-14 16 45 44](https://user-images.githubusercontent.com/11875540/81919747-6eb9e900-9602-11ea-9759-71f33c62b9d5.png)

**Comment by marckraw** [comment]
I have the same problem as @rikyperdana :) (while doing everything what was in readme)

**Comment by MarcHanin** [comment]
Thanks for reporting this error, this is the same bug as https://github.com/denoland/deno/issues/5319
I fixed that with an upgrade to `std@v0.51.0`

**Comment by marckraw** [comment]
@MarcHanin yup, now it's working, thx 👍
