### ISSUE TITLE
Allow setting of ENTRY_POINT_ALLOWED_EXTENSIONS in config

### ISSUE THREAD

**Issue by vospascal** [MarcHanin/drun#16]
If been playing with Deno and i wanned to use a .tsx file and DRUN only support ts and js files i can see using jsx files also would be an option so might be an idea to support more the just .js and .ts files

**Comment by MarcHanin** [comment]
Hi @vospascal,
Thanks for reporting this issue.
You're right,  `.tsx` and `.jsx` must be allowed, I will take the point.

**Comment by MarcHanin** [comment]
It will be part of the next release.
If you want to use it now you can use the `master` version
` deno install --allow-read --allow-run --unstable -f https://deno.land/x/drun/drun.ts`
