### ISSUE TITLE
I can't install drun

### ISSUE THREAD

**Issue by CesarV404** [MarcHanin/drun#23]
I try to install drun using 

`deno install --allow-read --allow-run --unstable https://deno.land/x/drun@v1.2.0/drun.ts`

and i got this error

![Captura de pantalla (31)](https://user-images.githubusercontent.com/46652735/90989478-9f91ae80-e55f-11ea-93bc-ce1e665d02d7.png)

Im using:
- windows 8.1
- Deno 1.3.1
- v8 8.6.334
- typescript 3.9.7

Help me u.u

**Comment by MarcHanin** [comment]
Hi @CesarRawr 
Thanks for reporting this issue, I fixed that in the new version, you can now install it with:
`deno install --allow-read --allow-run --unstable https://deno.land/x/drun/drun.ts`
